on: [push]

jobs:
  notion_learn_section:
    runs-on: ubuntu-latest
    name: A job to fetch and update learn section from notion
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main
      - name: Learn Section action step
        id: learn_section
        uses: devorein/github-action-learn-section-notion@v0.0.20
        with:
          database_id: "6c46c1eb-c5a4-4db7-8e3f-5fe285071ab6"
          token_v2: ${{ secrets.NOTION_TOKEN_V2 }}
